Models/Genero.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;

namespace PracticoLaboratorio4.Models
{
    public class Genero
    {
        public int Id { get; set; }

        [Required]
        [StringLength(20)]
        [MaxLength(20)]
        [DisplayName("Descripción")]
        [Remote(
            action: "ValidateDescripcion",
            controller: "Generos",
            AdditionalFields = nameof(Id),
            ErrorMessage = "Este género ya existe en la base de datos."
        )]
        public string Descripcion { get; set; }

        public List<Pelicula> Peliculas { get; set; }
    }
}

Controllers/DirectoresController.cs
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PracticoLaboratorio4.Data;
using PracticoLaboratorio4.Models;
using PracticoLaboratorio4.Utils;
using Microsoft.AspNetCore.Hosting;

namespace PracticoLaboratorio4.Controllers
{
    public class DirectoresController : Controller
    {
        private readonly ApplicationDbContext _context;

        private const string ImagePathWeb = "/img/directores/";
        private readonly string imagePathServer;

        public DirectoresController(ApplicationDbContext context, IWebHostEnvironment env)
        {
            _context = context;

            imagePathServer = Path.Combine(env.WebRootPath, "img", "directores");
        }

        // GET: Directores
        public async Task<IActionResult> Index(int? pageNumber)
        {
            int pageSize = 5;
            return View(await PaginatedList<Director>.CreateAsync(
                _context.Directores.AsNoTracking().OrderBy(d => d.Nombre),
                pageNumber ?? 1,
                pageSize
            ));
        }

        // GET: Directores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var director = await _context.Directores
                .Include(m => m.Peliculas)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (director == null)
            {
                return NotFound();
            }

            return View(director);
        }

        // GET: Directores/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Directores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Biografia,Foto")] Director director)
        {
            if (ModelState.IsValid)
            {
                if (director.Foto != null)
                {
                    director.UrlFoto = ImagePathWeb + FileManager.Create(director.Foto, imagePathServer);
                }
                _context.Add(director);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(director);
        }

        // GET: Directores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var director = await _context.Directores.FindAsync(id);
            if (director == null)
            {
                return NotFound();
            }
            return View(director);
        }

        // POST: Directores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Biografia,Foto,UrlFoto")] Director director)
        {
            if (id != director.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (director.Foto != null)
                {
                    if (!string.IsNullOrEmpty(director.UrlFoto))
                    {
                        FileManager.Delete(Path.Combine(imagePathServer, director.UrlFoto.Split('/').Last()));
                    }

                    director.UrlFoto = ImagePathWeb + FileManager.Create(director.Foto, imagePathServer);
                }

                try
                {
                    _context.Update(director);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DirectorExists(director.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(director);
        }

        // GET: Directores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var director = await _context.Directores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (director == null)
            {
                return NotFound();
            }

            return View(director);
        }

        // POST: Directores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var director = await _context.Directores.FindAsync(id);

            if (!string.IsNullOrEmpty(director.UrlFoto))
            {
                FileManager.Delete(Path.Combine(imagePathServer, director.UrlFoto.Split('/').Last()));
            }

            _context.Directores.Remove(director);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DirectorExists(int id)
        {
            return _context.Directores.Any(e => e.Id == id);
        }
    }
}

Controllers/PeliculasController.cs
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PracticoLaboratorio4.Data;
using PracticoLaboratorio4.Models;
using PracticoLaboratorio4.Utils;

namespace PracticoLaboratorio4.Controllers
{
    public class PeliculasController : Controller
    {
        private readonly ApplicationDbContext _context;

        private const string ImagePathWeb = "/img/peliculas/";
        private readonly string imagePathServer;

        public PeliculasController(ApplicationDbContext context, IWebHostEnvironment env)
        {
            _context = context;

            imagePathServer = Path.Combine(env.WebRootPath, "img", "peliculas");
        }

        // GET: Peliculas
        public async Task<IActionResult> Index(int? pageNumber)
        {
            int pageSize = 5;
            return View(await PaginatedList<Pelicula>.CreateAsync(
                _context.Peliculas
                    .AsNoTracking()
                    .Include(p => p.Genero)
                    .Include(p => p.Director)
                    .OrderBy(p => p.Titulo),
                pageNumber ?? 1,
                pageSize
            ));
        }

        // GET: Peliculas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pelicula = await _context.Peliculas
                .Include(p => p.Director)
                .Include(p => p.Genero)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pelicula == null)
            {
                return NotFound();
            }

            return View(pelicula);
        }

        // GET: Peliculas/Create
        public IActionResult Create()
        {
            ViewData["DirectorId"] = new SelectList(
                _context.Directores.AsNoTracking().OrderBy(d => d.Nombre),
                "Id",
                "Nombre"
            );

            ViewData["GeneroId"] = new SelectList(
                _context.Generos.AsNoTracking().OrderBy(g => g.Descripcion),
                "Id",
                "Descripcion"
            );

            return View();
        }

        // POST: Peliculas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Titulo,GeneroId,DirectorId,Resumen,FechaEstreno,ImagenPortada,Trailer")] Pelicula pelicula)
        {
            if (ModelState.IsValid)
            {
                if (pelicula.ImagenPortada != null)
                {
                    pelicula.UrlImagenPortada = ImagePathWeb + FileManager.Create(pelicula.ImagenPortada, imagePathServer);
                }

                _context.Add(pelicula);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["DirectorId"] = new SelectList(
                _context.Directores.AsNoTracking().OrderBy(d => d.Nombre),
                "Id",
                "Nombre"
            );

            ViewData["GeneroId"] = new SelectList(
                _context.Generos.AsNoTracking().OrderBy(g => g.Descripcion),
                "Id",
                "Descripcion"
            );

            return View(pelicula);
        }

        // GET: Peliculas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pelicula = await _context.Peliculas.FindAsync(id);
            if (pelicula == null)
            {
                return NotFound();
            }

            ViewData["DirectorId"] = new SelectList(
                _context.Directores.AsNoTracking().OrderBy(d => d.Nombre),
                "Id",
                "Nombre"
            );

            ViewData["GeneroId"] = new SelectList(
                _context.Generos.AsNoTracking().OrderBy(g => g.Descripcion),
                "Id",
                "Descripcion"
            );

            return View(pelicula);
        }

        // POST: Peliculas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Titulo,GeneroId,DirectorId,Resumen,FechaEstreno,ImagenPortada,UrlImagenPortada,Trailer")] Pelicula pelicula)
        {
            if (id != pelicula.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (pelicula.ImagenPortada != null)
                {
                    if (!string.IsNullOrEmpty(pelicula.UrlImagenPortada))
                    {
                        FileManager.Delete(Path.Combine(imagePathServer, pelicula.UrlImagenPortada.Split('/').Last()));
                    }

                    pelicula.UrlImagenPortada = ImagePathWeb + FileManager.Create(pelicula.ImagenPortada, imagePathServer);
                }

                try
                {
                    _context.Update(pelicula);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PeliculaExists(pelicula.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["DirectorId"] = new SelectList(
                _context.Directores.AsNoTracking().OrderBy(d => d.Nombre),
                "Id",
                "Nombre"
            );

            ViewData["GeneroId"] = new SelectList(
                _context.Generos.AsNoTracking().OrderBy(g => g.Descripcion),
                "Id",
                "Descripcion"
            );

            return View(pelicula);
        }

        // GET: Peliculas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pelicula = await _context.Peliculas
                .Include(p => p.Director)
                .Include(p => p.Genero)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pelicula == null)
            {
                return NotFound();
            }

            return View(pelicula);
        }

        // POST: Peliculas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pelicula = await _context.Peliculas.FindAsync(id);

            if (!string.IsNullOrEmpty(pelicula.UrlImagenPortada))
            {
                FileManager.Delete(Path.Combine(imagePathServer, pelicula.UrlImagenPortada.Split('/').Last()));
            }

            _context.Peliculas.Remove(pelicula);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PeliculaExists(int id)
        {
            return _context.Peliculas.Any(e => e.Id == id);
        }
    }
}

Views/Generos/Create.cshtml
@model PracticoLaboratorio4.Models.Genero

@{
    ViewData["Title"] = "Crear";
}

<h1>Crear</h1>

<h4>Género</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Crear</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Generos/Delete.cshtml
@model PracticoLaboratorio4.Models.Genero

@{
    ViewData["Title"] = "Eliminar";
}

<h1>Eliminar</h1>

<h3>¿Estás seguro de querer borrar este elemento?</h3>
<div>
    <h4>Género</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <button type="submit" class="btn btn-danger">Eliminar</button> |
        <a asp-action="Index">Volver a la lista</a>
    </form>
</div>

Views/Generos/Details.cshtml
@model PracticoLaboratorio4.Models.Genero
@using System.Linq;

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles</h1>

<div>
    <h4>Género</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
    </dl>
</div>
<div>
    <h5>Películas disponibles de este género</h5>
    @{
        if(Model.Peliculas.Any())
        {
            <ul>
                @foreach (Pelicula pelicula in Model.Peliculas)
                {
                    <li>
                        <a asp-controller="Peliculas" asp-action="Details" asp-route-id="@pelicula.Id">
                            @(pelicula.Titulo) (@(pelicula.FechaEstreno.Year))
                        </a>, de
                        <a
                            asp-controller="Directores"
                            asp-action="Details"
                            asp-route-id="@pelicula.DirectorId"
                        >
                            @pelicula.Director.Nombre
                        </a>
                    </li>
                }
            </ul>
        }
        else
        {
            <p>Todavía no hay películas de este género en nuestra base de datos.</p>
        }
    }
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Editar</a> |
    <a asp-action="Index">Volver a la lista</a>
</div>

Views/Generos/Edit.cshtml
@model PracticoLaboratorio4.Models.Genero

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>Género</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Generos/Index.cshtml
@model IEnumerable<PracticoLaboratorio4.Models.Genero>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Crear Nuevo</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Detalles</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Borrar</a>
            </td>
        </tr>
}
    </tbody>
</table>