Models/Pelicula.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Http;
using System.ComponentModel;
using PracticoLaboratorio4.Validators;

namespace PracticoLaboratorio4.Models
{
    public class Pelicula
    {
        public int Id { get; set; }

        [Required]
        [StringLength(20)]
        [MaxLength(20)]
        [DisplayName("Título")]
        public string Titulo { get; set; }

        [Required]
        [DisplayName("Género")]
        public int GeneroId { get; set; }

        [DisplayName("Género")]
        public Genero Genero { get; set; }

        [Required]
        [DisplayName("Director")]
        public int DirectorId { get; set; }

        public Director Director { get; set; }

        [StringLength(500)]
        [MaxLength(500)]
        public string Resumen { get; set; }

        [Required]
        [DisplayName("Fecha de estreno")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime FechaEstreno { get; set; }

        [MaxLength(1000)]
        public string UrlImagenPortada { get; set; }

        [NotMapped]
        [DisplayName("Portada")]
        [MinFileSize]
        [MaxFileSize(8 * 1024 * 1024)]
        [AllowedExtensions(".jpg", ".jpeg", ".png")]
        public IFormFile ImagenPortada { get; set; }

        [Url]
        [StringLength(1000)]
        [MaxLength(1000)]
        public string Trailer { get; set; }
    }
}

Controllers/DirectoresController.cs
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PracticoLaboratorio4.Data;
using PracticoLaboratorio4.Models;
using PracticoLaboratorio4.Utils;
using Microsoft.AspNetCore.Hosting;

namespace PracticoLaboratorio4.Controllers
{
    public class DirectoresController : Controller
    {
        private readonly ApplicationDbContext _context;

        private const string ImagePathWeb = "/img/directores/";
        private readonly string imagePathServer;

        public DirectoresController(ApplicationDbContext context, IWebHostEnvironment env)
        {
            _context = context;

            imagePathServer = Path.Combine(env.WebRootPath, "img", "directores");
        }

        // GET: Directores
        public async Task<IActionResult> Index(int? pageNumber)
        {
            int pageSize = 5;
            return View(await PaginatedList<Director>.CreateAsync(
                _context.Directores.AsNoTracking().OrderBy(d => d.Nombre),
                pageNumber ?? 1,
                pageSize
            ));
        }

        // GET: Directores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var director = await _context.Directores
                .Include(m => m.Peliculas)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (director == null)
            {
                return NotFound();
            }

            return View(director);
        }

        // GET: Directores/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Directores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Biografia,Foto")] Director director)
        {
            if (ModelState.IsValid)
            {
                if (director.Foto != null)
                {
                    director.UrlFoto = ImagePathWeb + FileManager.Create(director.Foto, imagePathServer);
                }
                _context.Add(director);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(director);
        }

        // GET: Directores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var director = await _context.Directores.FindAsync(id);
            if (director == null)
            {
                return NotFound();
            }
            return View(director);
        }

        // POST: Directores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Biografia,Foto,UrlFoto")] Director director)
        {
            if (id != director.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (director.Foto != null)
                {
                    if (!string.IsNullOrEmpty(director.UrlFoto))
                    {
                        FileManager.Delete(Path.Combine(imagePathServer, director.UrlFoto.Split('/').Last()));
                    }

                    director.UrlFoto = ImagePathWeb + FileManager.Create(director.Foto, imagePathServer);
                }

                try
                {
                    _context.Update(director);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DirectorExists(director.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(director);
        }

        // GET: Directores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var director = await _context.Directores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (director == null)
            {
                return NotFound();
            }

            return View(director);
        }

        // POST: Directores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var director = await _context.Directores.FindAsync(id);

            if (!string.IsNullOrEmpty(director.UrlFoto))
            {
                FileManager.Delete(Path.Combine(imagePathServer, director.UrlFoto.Split('/').Last()));
            }

            _context.Directores.Remove(director);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DirectorExists(int id)
        {
            return _context.Directores.Any(e => e.Id == id);
        }
    }
}

Controllers/GenerosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PracticoLaboratorio4.Data;
using PracticoLaboratorio4.Models;

namespace PracticoLaboratorio4.Controllers
{
    public class GenerosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GenerosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Generos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Generos.AsNoTracking().OrderBy(g => g.Descripcion).ToListAsync());
        }

        // GET: Generos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genero = await _context.Generos
                .Include(m => m.Peliculas)
                .ThenInclude(p => p.Director)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (genero == null)
            {
                return NotFound();
            }

            return View(genero);
        }

        // GET: Generos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Generos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Descripcion")] Genero genero)
        {
            if (ModelState.IsValid)
            {
                _context.Add(genero);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(genero);
        }

        // GET: Generos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genero = await _context.Generos.FindAsync(id);
            if (genero == null)
            {
                return NotFound();
            }
            return View(genero);
        }

        // POST: Generos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Descripcion")] Genero genero)
        {
            if (id != genero.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(genero);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GeneroExists(genero.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genero);
        }

        // GET: Generos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genero = await _context.Generos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (genero == null)
            {
                return NotFound();
            }

            return View(genero);
        }

        // POST: Generos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var genero = await _context.Generos.FindAsync(id);
            _context.Generos.Remove(genero);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GeneroExists(int id)
        {
            return _context.Generos.Any(e => e.Id == id);
        }

        [AcceptVerbs("GET", "POST")]
        public async Task<IActionResult> ValidateDescripcion(string descripcion, int id)
        {
            return Json(!(await _context.Generos.AnyAsync(g =>
                g.Descripcion == descripcion && g.Id != id
            )));
        }
    }
}

Views/Peliculas/Create.cshtml
@model PracticoLaboratorio4.Models.Pelicula

@{
    ViewData["Title"] = "Crear";
}

<h1>Crear</h1>

<h4>Película</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GeneroId" class="control-label"></label>
                <select asp-for="GeneroId" class ="form-control" asp-items="ViewBag.GeneroId">
                    <option selected disabled>Seleccione uno...</option>
                </select>
                <span asp-validation-for="GeneroId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DirectorId" class="control-label"></label>
                <select asp-for="DirectorId" class ="form-control" asp-items="ViewBag.DirectorId">
                    <option selected disabled>Seleccione uno...</option>
                </select>
                <span asp-validation-for="DirectorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Resumen" class="control-label"></label>
                <textarea asp-for="Resumen" class="form-control"></textarea>
                <span asp-validation-for="Resumen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaEstreno" class="control-label"></label>
                <input type="date" asp-for="FechaEstreno" asp-format="{0:yyyy-MM-dd}" class="form-control" />
                <span asp-validation-for="FechaEstreno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagenPortada" class="control-label"></label>
                <input
                    asp-for="ImagenPortada"
                    type="file"
                    accept="image/png, image/jpg, image/jpeg"
                    class="form-control"
                    id="foto-input"
                />
                <span asp-validation-for="ImagenPortada" class="text-danger"></span>
            </div>
            <div class="form-group foto-pelicula">
                <img src="" class="img-thumbnail img-fluid" id="foto">
            </div>
            <div class="form-group">
                <label asp-for="Trailer" class="control-label"></label>
                <input asp-for="Trailer" class="form-control" />
                <span asp-validation-for="Trailer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" value="Create" class="btn btn-primary">Crear</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/js/imageSelector.js"></script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Peliculas/Delete.cshtml
@model PracticoLaboratorio4.Models.Pelicula

@{
    ViewData["Title"] = "Eliminar";
}

<h1>Eliminar</h1>

<h3>¿Estás seguro de querer borrar este elemento?</h3>
<div>
    <h4>Pelicula</h4>
    <hr />
    @{
        if (!string.IsNullOrEmpty(@Model.UrlImagenPortada))
        {
            <div class="foto-pelicula">
                <img src="@Model.UrlImagenPortada" alt="portada" class="img-fluid img-thumbnail">
            </div>
        }
    }
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero.Descripcion)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Director)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Director.Nombre)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaEstreno)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaEstreno)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Peliculas/Details.cshtml
@model PracticoLaboratorio4.Models.Pelicula

@{
    ViewData["Title"] = "Detalles";
}

<h1>Detalles</h1>

<div>
    <h4>Película</h4>
    <hr />
    @{
        if (!string.IsNullOrEmpty(Model.UrlImagenPortada)) {
            <div class="foto-pelicula">
                <img src="@Model.UrlImagenPortada" alt="portada" class="img-fluid img-thumbnail">
            </div>
        }
    }
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            <a asp-controller="Generos" asp-action="Details" asp-route-id="@Model.GeneroId">
                @Html.DisplayFor(model => model.Genero.Descripcion)
            </a>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Director)
        </dt>
        <dd class = "col-sm-10">
            <a asp-controller="Directores" asp-action="Details" asp-route-id="@Model.DirectorId">
                @Html.DisplayFor(model => model.Director.Nombre)
            </a>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Resumen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Resumen)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaEstreno)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaEstreno)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Trailer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Trailer)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Editar</a> |
    <a asp-action="Index">Volver a la lista</a>
</div>

Views/Peliculas/Edit.cshtml
@model PracticoLaboratorio4.Models.Pelicula

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>Pelicula</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GeneroId" class="control-label"></label>
                <select asp-for="GeneroId" class="form-control" asp-items="ViewBag.GeneroId"></select>
                <span asp-validation-for="GeneroId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DirectorId" class="control-label"></label>
                <select asp-for="DirectorId" class="form-control" asp-items="ViewBag.DirectorId"></select>
                <span asp-validation-for="DirectorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Resumen" class="control-label"></label>
                <textarea asp-for="Resumen" class="form-control"></textarea>
                <span asp-validation-for="Resumen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaEstreno" class="control-label"></label>
                <input type="date" asp-for="FechaEstreno" asp-format="{0:yyyy-MM-dd}" class="form-control" />
                <span asp-validation-for="FechaEstreno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagenPortada" class="control-label"></label>
                <input
                    asp-for="ImagenPortada"
                    type="file"
                    accept="image/png, image/jpg, image/jpeg"
                    class="form-control"
                    id="foto-input"
                />
                <span asp-validation-for="ImagenPortada" class="text-danger"></span>
                <input type="hidden" asp-for="UrlImagenPortada">
            </div>
            <div class="form-group foto-pelicula">
                <img src="@Model.UrlImagenPortada" class="img-thumbnail img-fluid" id="foto">
            </div>
            <div class="form-group">
                <label asp-for="Trailer" class="control-label"></label>
                <input asp-for="Trailer" class="form-control" />
                <span asp-validation-for="Trailer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/js/imageSelector.js"></script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Peliculas/Index.cshtml
@model PaginatedList<PracticoLaboratorio4.Models.Pelicula>

@{
    ViewData["Title"] = "Index";
}

<h1>Películas</h1>

<p>
    <a asp-action="Create">Crear Nuevo</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Portada
            </th>
            <th>
                Titulo
            </th>
            <th>
                Genero
            </th>
            <th>
                Director
            </th>
            <th>
                Fecha de estreno
            </th>
            <th>
                Trailer
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @{
                    if (!string.IsNullOrEmpty(item.UrlImagenPortada))
                    {
                        <div class="foto-pelicula">
                            <img src="@item.UrlImagenPortada" alt="portada" class="img-fluid img-thumbail">
                        </div>
                    }
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                <a asp-controller="Generos" asp-action="Details" asp-route-id="@item.GeneroId">
                    @Html.DisplayFor(modelItem => item.Genero.Descripcion)
                </a>
            </td>
            <td>
                <a asp-controller="Directores" asp-action="Details" asp-route-id="@item.DirectorId">
                    @Html.DisplayFor(modelItem => item.Director.Nombre)
                </a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaEstreno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Trailer)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Detalles</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Borrar</a>
            </td>
        </tr>
}
    </tbody>
</table>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   class="btn btn-default @prevDisabled"
>
    Anterior
</a>
<a asp-action="Index"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   class="btn btn-default @nextDisabled"
>
    Siguiente
</a>